// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: fund/types.proto

package fund

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_fund_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_fund_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_fund_types_proto_rawDescGZIP(), []int{0}
}

type PongResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResp) Reset() {
	*x = PongResp{}
	mi := &file_fund_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResp) ProtoMessage() {}

func (x *PongResp) ProtoReflect() protoreflect.Message {
	mi := &file_fund_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResp.ProtoReflect.Descriptor instead.
func (*PongResp) Descriptor() ([]byte, []int) {
	return file_fund_types_proto_rawDescGZIP(), []int{1}
}

func (x *PongResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fund_types_proto protoreflect.FileDescriptor

const file_fund_types_proto_rawDesc = "" +
	"\n" +
	"\x10fund/types.proto\x12\x04fund\"\t\n" +
	"\aPingReq\"$\n" +
	"\bPongResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB*Z(github.com/liweiming-nova/pb/gen-go/fundb\x06proto3"

var (
	file_fund_types_proto_rawDescOnce sync.Once
	file_fund_types_proto_rawDescData []byte
)

func file_fund_types_proto_rawDescGZIP() []byte {
	file_fund_types_proto_rawDescOnce.Do(func() {
		file_fund_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_types_proto_rawDesc), len(file_fund_types_proto_rawDesc)))
	})
	return file_fund_types_proto_rawDescData
}

var file_fund_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fund_types_proto_goTypes = []any{
	(*PingReq)(nil),  // 0: fund.PingReq
	(*PongResp)(nil), // 1: fund.PongResp
}
var file_fund_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fund_types_proto_init() }
func file_fund_types_proto_init() {
	if File_fund_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_types_proto_rawDesc), len(file_fund_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fund_types_proto_goTypes,
		DependencyIndexes: file_fund_types_proto_depIdxs,
		MessageInfos:      file_fund_types_proto_msgTypes,
	}.Build()
	File_fund_types_proto = out.File
	file_fund_types_proto_goTypes = nil
	file_fund_types_proto_depIdxs = nil
}
