// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: email/services.proto

package email

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_email_services_proto protoreflect.FileDescriptor

const file_email_services_proto_rawDesc = "" +
	"\n" +
	"\x14email/services.proto\x12\x05email\x1a#third_party/validate/validate.proto\x1a\x11email/types.proto2H\n" +
	"\fEmailService\x128\n" +
	"\tSendEmail\x12\x13.email.SendEmailReq\x1a\x14.email.SendEmailResp\"\x00B+Z)github.com/liweiming-nova/pb/gen-go/emailb\x06proto3"

var file_email_services_proto_goTypes = []any{
	(*SendEmailReq)(nil),  // 0: email.SendEmailReq
	(*SendEmailResp)(nil), // 1: email.SendEmailResp
}
var file_email_services_proto_depIdxs = []int32{
	0, // 0: email.EmailService.SendEmail:input_type -> email.SendEmailReq
	1, // 1: email.EmailService.SendEmail:output_type -> email.SendEmailResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_services_proto_init() }
func file_email_services_proto_init() {
	if File_email_services_proto != nil {
		return
	}
	file_email_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_services_proto_rawDesc), len(file_email_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_services_proto_goTypes,
		DependencyIndexes: file_email_services_proto_depIdxs,
	}.Build()
	File_email_services_proto = out.File
	file_email_services_proto_goTypes = nil
	file_email_services_proto_depIdxs = nil
}
