// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: email/types.proto

package email

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendEmailReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendEmailReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendEmailReqMultiError, or
// nil if none found.
func (m *SendEmailReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetFrom()); err != nil {
		err = SendEmailReqValidationError{
			field:  "From",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetTo()) < 1 {
		err := SendEmailReqValidationError{
			field:  "To",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetTo() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) < 1 {
			err := SendEmailReqValidationError{
				field:  fmt.Sprintf("To[%v]", idx),
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if err := m._validateEmail(item); err != nil {
			err = SendEmailReqValidationError{
				field:  fmt.Sprintf("To[%v]", idx),
				reason: "value must be a valid email address",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	for idx, item := range m.GetCc() {
		_, _ = idx, item

		if err := m._validateEmail(item); err != nil {
			err = SendEmailReqValidationError{
				field:  fmt.Sprintf("Cc[%v]", idx),
				reason: "value must be a valid email address",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	for idx, item := range m.GetBcc() {
		_, _ = idx, item

		if err := m._validateEmail(item); err != nil {
			err = SendEmailReqValidationError{
				field:  fmt.Sprintf("Bcc[%v]", idx),
				reason: "value must be a valid email address",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if l := utf8.RuneCountInString(m.GetSubject()); l < 1 || l > 256 {
		err := SendEmailReqValidationError{
			field:  "Subject",
			reason: "value length must be between 1 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBodyText()) > 10000 {
		err := SendEmailReqValidationError{
			field:  "BodyText",
			reason: "value length must be at most 10000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBodyHtml()) > 50000 {
		err := SendEmailReqValidationError{
			field:  "BodyHtml",
			reason: "value length must be at most 50000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Headers

	if utf8.RuneCountInString(m.GetTemplateId()) > 128 {
		err := SendEmailReqValidationError{
			field:  "TemplateId",
			reason: "value length must be at most 128 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for TemplateParams

	if len(errors) > 0 {
		return SendEmailReqMultiError(errors)
	}

	return nil
}

func (m *SendEmailReq) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *SendEmailReq) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// SendEmailReqMultiError is an error wrapping multiple validation errors
// returned by SendEmailReq.ValidateAll() if the designated constraints aren't met.
type SendEmailReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailReqMultiError) AllErrors() []error { return m }

// SendEmailReqValidationError is the validation error returned by
// SendEmailReq.Validate if the designated constraints aren't met.
type SendEmailReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendEmailReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailReqValidationError) ErrorName() string { return "SendEmailReqValidationError" }

// Error satisfies the builtin error interface
func (e SendEmailReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendEmailReqValidationError{}

// Validate checks the field values on SendEmailResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendEmailResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendEmailRespMultiError, or
// nil if none found.
func (m *SendEmailResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if utf8.RuneCountInString(m.GetMessageId()) < 1 {
		err := SendEmailRespValidationError{
			field:  "MessageId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for SendTime

	if len(errors) > 0 {
		return SendEmailRespMultiError(errors)
	}

	return nil
}

// SendEmailRespMultiError is an error wrapping multiple validation errors
// returned by SendEmailResp.ValidateAll() if the designated constraints
// aren't met.
type SendEmailRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailRespMultiError) AllErrors() []error { return m }

// SendEmailRespValidationError is the validation error returned by
// SendEmailResp.Validate if the designated constraints aren't met.
type SendEmailRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendEmailRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailRespValidationError) ErrorName() string { return "SendEmailRespValidationError" }

// Error satisfies the builtin error interface
func (e SendEmailRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendEmailRespValidationError{}
