// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: email/types.proto

package email

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	From           string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from"`
	To             []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to"`
	Cc             []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc"`
	Bcc            []string               `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc"`
	Subject        string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject"`
	BodyText       string                 `protobuf:"bytes,6,opt,name=body_text,json=bodyText,proto3" json:"body_text"`
	BodyHtml       string                 `protobuf:"bytes,7,opt,name=body_html,json=bodyHtml,proto3" json:"body_html"`
	Headers        map[string]string      `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TemplateId     string                 `protobuf:"bytes,10,opt,name=template_id,json=templateId,proto3" json:"template_id"`
	TemplateParams map[string]string      `protobuf:"bytes,11,rep,name=template_params,json=templateParams,proto3" json:"template_params" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendEmailReq) Reset() {
	*x = SendEmailReq{}
	mi := &file_email_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReq) ProtoMessage() {}

func (x *SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_email_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReq.ProtoReflect.Descriptor instead.
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return file_email_types_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailReq) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailReq) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailReq) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailReq) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

func (x *SendEmailReq) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

func (x *SendEmailReq) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SendEmailReq) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendEmailReq) GetTemplateParams() map[string]string {
	if x != nil {
		return x.TemplateParams
	}
	return nil
}

type SendEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id"`
	SendTime      int64                  `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResp) Reset() {
	*x = SendEmailResp{}
	mi := &file_email_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResp) ProtoMessage() {}

func (x *SendEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_email_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResp.ProtoReflect.Descriptor instead.
func (*SendEmailResp) Descriptor() ([]byte, []int) {
	return file_email_types_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailResp) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendEmailResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

var File_email_types_proto protoreflect.FileDescriptor

const file_email_types_proto_rawDesc = "" +
	"\n" +
	"\x11email/types.proto\x12\x05email\x1a#third_party/validate/validate.proto\"\xb8\x04\n" +
	"\fSendEmailReq\x12\x1b\n" +
	"\x04from\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x04from\x12 \n" +
	"\x02to\x18\x02 \x03(\tB\x10\xfaB\r\x92\x01\n" +
	"\b\x01\"\x06r\x04\x10\x01`\x01R\x02to\x12\x1c\n" +
	"\x02cc\x18\x03 \x03(\tB\f\xfaB\t\x92\x01\x06\"\x04r\x02`\x01R\x02cc\x12\x1e\n" +
	"\x03bcc\x18\x04 \x03(\tB\f\xfaB\t\x92\x01\x06\"\x04r\x02`\x01R\x03bcc\x12$\n" +
	"\asubject\x18\x05 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x02R\asubject\x12%\n" +
	"\tbody_text\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x18\x90NR\bbodyText\x12&\n" +
	"\tbody_html\x18\a \x01(\tB\t\xfaB\x06r\x04\x18І\x03R\bbodyHtml\x12:\n" +
	"\aheaders\x18\t \x03(\v2 .email.SendEmailReq.HeadersEntryR\aheaders\x12)\n" +
	"\vtemplate_id\x18\n" +
	" \x01(\tB\b\xfaB\x05r\x03\x18\x80\x01R\n" +
	"templateId\x12P\n" +
	"\x0ftemplate_params\x18\v \x03(\v2'.email.SendEmailReq.TemplateParamsEntryR\x0etemplateParams\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13TemplateParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\rSendEmailResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmessageId\x12\x1b\n" +
	"\tsend_time\x18\x04 \x01(\x03R\bsendTimeB+Z)github.com/liweiming-nova/pb/gen-go/emailb\x06proto3"

var (
	file_email_types_proto_rawDescOnce sync.Once
	file_email_types_proto_rawDescData []byte
)

func file_email_types_proto_rawDescGZIP() []byte {
	file_email_types_proto_rawDescOnce.Do(func() {
		file_email_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_types_proto_rawDesc), len(file_email_types_proto_rawDesc)))
	})
	return file_email_types_proto_rawDescData
}

var file_email_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_email_types_proto_goTypes = []any{
	(*SendEmailReq)(nil),  // 0: email.SendEmailReq
	(*SendEmailResp)(nil), // 1: email.SendEmailResp
	nil,                   // 2: email.SendEmailReq.HeadersEntry
	nil,                   // 3: email.SendEmailReq.TemplateParamsEntry
}
var file_email_types_proto_depIdxs = []int32{
	2, // 0: email.SendEmailReq.headers:type_name -> email.SendEmailReq.HeadersEntry
	3, // 1: email.SendEmailReq.template_params:type_name -> email.SendEmailReq.TemplateParamsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_email_types_proto_init() }
func file_email_types_proto_init() {
	if File_email_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_types_proto_rawDesc), len(file_email_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_email_types_proto_goTypes,
		DependencyIndexes: file_email_types_proto_depIdxs,
		MessageInfos:      file_email_types_proto_msgTypes,
	}.Build()
	File_email_types_proto = out.File
	file_email_types_proto_goTypes = nil
	file_email_types_proto_depIdxs = nil
}
