// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: user/enum.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_StatusDisabledNIl Status = 0
	Status_StatusDisabled    Status = 1 //停用
	Status_StatusEnabled     Status = 2 //启用
	Status_StatusForbidden   Status = 3 // 禁用
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "StatusDisabledNIl",
		1: "StatusDisabled",
		2: "StatusEnabled",
		3: "StatusForbidden",
	}
	Status_value = map[string]int32{
		"StatusDisabledNIl": 0,
		"StatusDisabled":    1,
		"StatusEnabled":     2,
		"StatusForbidden":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{0}
}

var File_user_enum_proto protoreflect.FileDescriptor

const file_user_enum_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/enum.proto\x12\x04user\x1a#third_party/validate/validate.proto*[\n" +
	"\x06Status\x12\x15\n" +
	"\x11StatusDisabledNIl\x10\x00\x12\x12\n" +
	"\x0eStatusDisabled\x10\x01\x12\x11\n" +
	"\rStatusEnabled\x10\x02\x12\x13\n" +
	"\x0fStatusForbidden\x10\x03B*Z(github.com/liweiming-nova/pb/gen-go/userb\x06proto3"

var (
	file_user_enum_proto_rawDescOnce sync.Once
	file_user_enum_proto_rawDescData []byte
)

func file_user_enum_proto_rawDescGZIP() []byte {
	file_user_enum_proto_rawDescOnce.Do(func() {
		file_user_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_enum_proto_rawDesc), len(file_user_enum_proto_rawDesc)))
	})
	return file_user_enum_proto_rawDescData
}

var file_user_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_enum_proto_goTypes = []any{
	(Status)(0), // 0: user.Status
}
var file_user_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_enum_proto_init() }
func file_user_enum_proto_init() {
	if File_user_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_enum_proto_rawDesc), len(file_user_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_enum_proto_goTypes,
		DependencyIndexes: file_user_enum_proto_depIdxs,
		EnumInfos:         file_user_enum_proto_enumTypes,
	}.Build()
	File_user_enum_proto = out.File
	file_user_enum_proto_goTypes = nil
	file_user_enum_proto_depIdxs = nil
}
