// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: user/services.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_services_proto protoreflect.FileDescriptor

const file_user_services_proto_rawDesc = "" +
	"\n" +
	"\x13user/services.proto\x12\x04user\x1a#third_party/validate/validate.proto\x1a\x10user/types.proto2>\n" +
	"\n" +
	"UserServer\x120\n" +
	"\aGetUser\x12\x10.user.GetUserReq\x1a\x11.user.GetUserResp\"\x00B*Z(github.com/liweiming-nova/pb/gen-go/userb\x06proto3"

var file_user_services_proto_goTypes = []any{
	(*GetUserReq)(nil),  // 0: user.GetUserReq
	(*GetUserResp)(nil), // 1: user.GetUserResp
}
var file_user_services_proto_depIdxs = []int32{
	0, // 0: user.UserServer.GetUser:input_type -> user.GetUserReq
	1, // 1: user.UserServer.GetUser:output_type -> user.GetUserResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_services_proto_init() }
func file_user_services_proto_init() {
	if File_user_services_proto != nil {
		return
	}
	file_user_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_services_proto_rawDesc), len(file_user_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_services_proto_goTypes,
		DependencyIndexes: file_user_services_proto_depIdxs,
	}.Build()
	File_user_services_proto = out.File
	file_user_services_proto_goTypes = nil
	file_user_services_proto_depIdxs = nil
}
